# Generated by Django 4.2.20 on 2026-06-06 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomaineCarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du domaine')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icone', models.CharField(default='Map', max_length=50, verbose_name='Icône Lucide')),
                ('couleur', models.CharField(default='#22c55e', max_length=7, verbose_name='Couleur hex')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Domaine de carte',
                'verbose_name_plural': 'Domaines de cartes',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='CarteTheematique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250, verbose_name='Titre de la carte')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('vignette', models.ImageField(blank=True, null=True, upload_to='cartotheque/vignettes/', verbose_name='Vignette')),
                ('geojson_url', models.URLField(blank=True, max_length=500, verbose_name='URL GeoJSON externe')),
                ('geojson_file', models.FileField(blank=True, null=True, upload_to='cartotheque/geojson/', verbose_name='Fichier GeoJSON')),
                ('couches_associees', models.JSONField(blank=True, default=list, verbose_name='Couches associées')),
                ('centre_lat', models.FloatField(default=8.32, verbose_name='Latitude du centre')),
                ('centre_lng', models.FloatField(default=0.9797, verbose_name='Longitude du centre')),
                ('zoom_default', models.IntegerField(default=12, verbose_name='Zoom par défaut')),
                ('fond_carte', models.CharField(choices=[('osm', 'OpenStreetMap'), ('satellite', 'Satellite ESRI'), ('dark', 'CartoDB Dark')], default='osm', max_length=20, verbose_name='Fond de carte')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('auteur', models.CharField(blank=True, max_length=200, verbose_name='Auteur')),
                ('source', models.CharField(blank=True, max_length=300, verbose_name='Source des données')),
                ('mots_cles', models.CharField(blank=True, max_length=500, verbose_name='Mots-clés')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('domaine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartes', to='cartotheque.domainecarte', verbose_name='Domaine thématique')),
            ],
            options={
                'verbose_name': 'Carte thématique',
                'verbose_name_plural': 'Cartes thématiques',
                'ordering': ['-date_creation'],
            },
        ),
    ]
