# Generated by Django 4.2.20 on 2026-06-10 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartotheque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartetheematique',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Carte thematique', 'verbose_name_plural': 'Cartes thematiques'},
        ),
        migrations.AddField(
            model_name='cartetheematique',
            name='date_edition',
            field=models.DateField(blank=True, help_text='Date de publication/edition de la carte', null=True, verbose_name="Date d'edition"),
        ),
        migrations.AddField(
            model_name='cartetheematique',
            name='echelle',
            field=models.CharField(blank=True, help_text='Ex: 1:50000, 1:25000, 1:100000', max_length=50, verbose_name='Echelle'),
        ),
        migrations.AddField(
            model_name='cartetheematique',
            name='format_impression',
            field=models.CharField(blank=True, choices=[('A0', 'A0 (841 x 1189 mm)'), ('A1', 'A1 (594 x 841 mm)'), ('A2', 'A2 (420 x 594 mm)'), ('A3', 'A3 (297 x 420 mm)'), ('A4', 'A4 (210 x 297 mm)'), ('personnalise', 'Personnalise')], max_length=20, verbose_name="Format d'impression"),
        ),
        migrations.AddField(
            model_name='cartetheematique',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cartotheque/images/', verbose_name='Image de la carte'),
        ),
        migrations.AddField(
            model_name='cartetheematique',
            name='is_payant',
            field=models.BooleanField(default=False, help_text='Indique si la carte est payante', verbose_name='Payant'),
        ),
        migrations.AddField(
            model_name='cartetheematique',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix en Francs CFA si la carte est payante', max_digits=10, null=True, verbose_name='Prix (F CFA)'),
        ),
        migrations.AddField(
            model_name='cartetheematique',
            name='realisateur',
            field=models.CharField(blank=True, help_text='Personne ou organisme qui a realise la carte', max_length=200, verbose_name='Realisateur'),
        ),
        migrations.AlterField(
            model_name='cartetheematique',
            name='couches_associees',
            field=models.JSONField(blank=True, default=list, verbose_name='Couches associees'),
        ),
        migrations.AlterField(
            model_name='cartetheematique',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de creation'),
        ),
        migrations.AlterField(
            model_name='cartetheematique',
            name='domaine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartes', to='cartotheque.domainecarte', verbose_name='Domaine thematique'),
        ),
        migrations.AlterField(
            model_name='cartetheematique',
            name='mots_cles',
            field=models.CharField(blank=True, max_length=500, verbose_name='Mots-cles'),
        ),
        migrations.AlterField(
            model_name='cartetheematique',
            name='source',
            field=models.CharField(blank=True, max_length=300, verbose_name='Source des donnees'),
        ),
        migrations.AlterField(
            model_name='cartetheematique',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publie'), ('archive', 'Archive')], default='brouillon', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='cartetheematique',
            name='zoom_default',
            field=models.IntegerField(default=12, verbose_name='Zoom par defaut'),
        ),
        migrations.AlterField(
            model_name='domainecarte',
            name='icone',
            field=models.CharField(default='Map', max_length=50, verbose_name='Icone Lucide'),
        ),
    ]
