# Generated by Django 4.2.20 on 2026-04-02 22:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('commune', models.CharField(max_length=100)),
                ('prefecture', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'communes_togo_utm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prefecture', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'couche_prefecture_utm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Champ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('proprietaire', models.CharField(max_length=200)),
                ('type_culture', models.CharField(max_length=100)),
                ('date_semi', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agriculture_champ',
            },
        ),
    ]
