# Generated by Django 4.2.20 on 2026-05-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la culture')),
                ('crop_type', models.CharField(choices=[('CEREAL', 'Céréale'), ('LEGUME', 'Légume'), ('TUBERCULE', 'Tubercule'), ('LEGUMINEUSE', 'Légumineuse')], max_length=20, verbose_name='Type')),
                ('sowing_start', models.IntegerField(verbose_name='Début Semi (Mois)')),
                ('sowing_end', models.IntegerField(verbose_name='Fin Semi (Mois)')),
                ('weeding_start', models.IntegerField(verbose_name='Début Sarclage (Mois)')),
                ('weeding_end', models.IntegerField(verbose_name='Fin Sarclage (Mois)')),
                ('harvest_start', models.IntegerField(verbose_name='Début Récolte (Mois)')),
                ('harvest_end', models.IntegerField(verbose_name='Fin Récolte (Mois)')),
                ('other_activities', models.TextField(blank=True, null=True, verbose_name='Autres activités (Fertilisation, etc.)')),
            ],
            options={
                'verbose_name': 'Calendrier Cultural',
                'verbose_name_plural': 'Calendriers Culturaux',
                'db_table': 'agriculture_crop_calendar',
            },
        ),
    ]
