# Generated by Django 4.2.20 on 2026-05-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0002_cropcalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropcalendar',
            name='duration_days',
            field=models.IntegerField(default=90, verbose_name='Durée cycle (jours)'),
        ),
        migrations.AddField(
            model_name='cropcalendar',
            name='variety',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Variété'),
        ),
        migrations.AlterField(
            model_name='cropcalendar',
            name='other_activities',
            field=models.TextField(blank=True, null=True, verbose_name='Autres activités'),
        ),
    ]
