# Generated by Django 4.2.20 on 2026-09-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0004_champ_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champ',
            name='owner',
        ),
    ]
