# Generated by Django 5.2.6 on 2026-09-08 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0006_champ_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('indicator', models.CharField(choices=[('SPI_1', 'SPI 1 mois'), ('SPI_3', 'SPI 3 mois'), ('SPI_6', 'SPI 6 mois'), ('SPI_FORECAST', 'SPI prévisionnel'), ('NDVI', 'NDVI'), ('EVI', 'EVI'), ('NDWI', 'NDWI'), ('VCI', 'VCI'), ('TCI', 'TCI'), ('VHI', 'VHI'), ('NCWSI', 'NCWSI'), ('RAINFALL', 'Précipitations'), ('TEMPERATURE', 'Température')], max_length=30)),
                ('operator', models.CharField(choices=[('LT', 'LT'), ('LTE', 'LTE'), ('GT', 'GT'), ('GTE', 'GTE'), ('EQ', 'EQ'), ('CHANGE_PCT', 'CHANGE_PCT')], max_length=15)),
                ('threshold', models.FloatField()),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('title_template', models.CharField(max_length=255)),
                ('message_template', models.TextField()),
                ('recommendation_template', models.TextField(blank=True)),
                ('crop_type', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('cooldown_hours', models.PositiveIntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['indicator', 'severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FarmerAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(choices=[('SPI_1', 'SPI 1 mois'), ('SPI_3', 'SPI 3 mois'), ('SPI_6', 'SPI 6 mois'), ('SPI_FORECAST', 'SPI prévisionnel'), ('NDVI', 'NDVI'), ('EVI', 'EVI'), ('NDWI', 'NDWI'), ('VCI', 'VCI'), ('TCI', 'TCI'), ('VHI', 'VHI'), ('NCWSI', 'NCWSI'), ('RAINFALL', 'Précipitations'), ('TEMPERATURE', 'Température')], max_length=30)),
                ('observed_value', models.FloatField()),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('EXPIRED', 'Expired')], db_index=True, default='OPEN', max_length=15)),
                ('observed_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('champ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_alerts', to='agriculture.champ')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_alerts', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='agriculture.alertrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'Whatsapp')], max_length=15)),
                ('destination', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=10)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='agriculture.farmeralert')),
            ],
        ),
        migrations.CreateModel(
            name='FieldIndicatorSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('indicator', models.CharField(choices=[('SPI_1', 'SPI 1 mois'), ('SPI_3', 'SPI 3 mois'), ('SPI_6', 'SPI 6 mois'), ('SPI_FORECAST', 'SPI prévisionnel'), ('NDVI', 'NDVI'), ('EVI', 'EVI'), ('NDWI', 'NDWI'), ('VCI', 'VCI'), ('TCI', 'TCI'), ('VHI', 'VHI'), ('NCWSI', 'NCWSI'), ('RAINFALL', 'Précipitations'), ('TEMPERATURE', 'Température')], db_index=True, max_length=30)),
                ('value', models.FloatField()),
                ('reference_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('champ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_snapshots', to='agriculture.champ')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='farmeralert',
            index=models.Index(fields=['farmer', 'status', '-created_at'], name='agriculture_farmer__24d28c_idx'),
        ),
        migrations.AddIndex(
            model_name='alertdelivery',
            index=models.Index(fields=['channel', 'status', 'created_at'], name='agriculture_channel_9f80eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='alertdelivery',
            constraint=models.UniqueConstraint(fields=('alert', 'channel'), name='unique_alert_delivery_channel'),
        ),
        migrations.AddIndex(
            model_name='fieldindicatorsnapshot',
            index=models.Index(fields=['champ', 'indicator', '-observed_at'], name='agriculture_champ_i_045e78_idx'),
        ),
        migrations.AddConstraint(
            model_name='fieldindicatorsnapshot',
            constraint=models.UniqueConstraint(fields=('champ', 'observed_at', 'indicator'), name='unique_field_indicator_observation'),
        ),
    ]
