# Generated by Django 4.2.20 on 2026-09-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0009_risk_engine'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='farmeralert',
            new_name='agriculture_champ_i_f4e4b0_idx',
            old_name='agri_farmeralert_champ_type_idx',
        ),
        migrations.RenameIndex(
            model_name='farmeralert',
            new_name='agriculture_farmer__78f2bd_idx',
            old_name='agri_farmeralert_risk_idx',
        ),
        migrations.RenameIndex(
            model_name='riskassessment',
            new_name='agriculture_champ_i_ba5584_idx',
            old_name='agri_risk_champ_idx',
        ),
        migrations.RenameIndex(
            model_name='riskassessment',
            new_name='agriculture_level_568c17_idx',
            old_name='agri_risk_level_idx',
        ),
        migrations.AlterField(
            model_name='farmeralert',
            name='indicator',
            field=models.CharField(choices=[('NDVI', 'NDVI'), ('EVI', 'EVI'), ('NDWI', 'NDWI'), ('MSAVI', 'MSAVI'), ('VCI', 'VCI'), ('TCI', 'TCI'), ('VHI', 'VHI'), ('NCWSI', 'NCWSI'), ('SPI_30', 'SPI 30 jours'), ('SPI_90', 'SPI 90 jours'), ('SPI_FORECAST', 'SPI prévisionnel 15 jours'), ('RAINFALL_24H', 'Précipitations 24 h'), ('RAINFALL_72H', 'Précipitations 72 h'), ('SPI_1', 'SPI 1 mois (alias)'), ('SPI_3', 'SPI 3 mois (alias)'), ('SPI_6', 'SPI 6 mois (alias)'), ('RAINFALL', 'Précipitations (générique)'), ('TEMPERATURE', 'Température')], max_length=30),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
