# Generated by Django 5.2.6 on 2026-09-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recevoir_alertes_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recevoir_alertes_whatsapp',
            field=models.BooleanField(default=False),
        ),
    ]
