# Generated by Django 4.2.20 on 2026-09-12 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_recevoir_alertes_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='recevoir_alertes_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='recevoir_alertes_whatsapp',
        ),
    ]
