# Generated by Django 4.2.20 on 2026-01-04 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoportail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quartieraneho',
            table='qartier_aneho',
        ),
    ]
