# Generated by Django 4.2.20 on 2026-01-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoportail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quartier',
            table='quartier_l1',
        ),
    ]
