# Generated by Django 4.2.20 on 2026-01-05 13:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportail', '0002_alter_quartier_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(max_length=100)),
                ('route_clas', models.CharField(max_length=100)),
                ('route_reco', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'routess',
                'managed': False,
            },
        ),
    ]
