# Generated by Django 4.2.20 on 2026-01-04 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoportail', '0002_alter_quartieraneho_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quartieraneho',
            options={'managed': False},
        ),
    ]
