# Generated by Django 4.2.20 on 2026-01-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoportail', '0003_routes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quartier',
        ),
        migrations.AlterModelTable(
            name='cantons',
            table='cant_bli2',
        ),
        migrations.AlterModelTable(
            name='commune',
            table='blitta_2',
        ),
        migrations.AlterModelTable(
            name='routes',
            table='route_b2',
        ),
    ]
