# Generated by Django 4.2.20 on 2026-01-28 11:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportail', '0004_delete_quartier_alter_cantons_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canton_nom', models.CharField(max_length=100)),
                ('nom_locali', models.CharField(max_length=100)),
                ('etablissem', models.CharField(max_length=100)),
                ('etab_adr', models.CharField(max_length=100)),
                ('ouverture', models.CharField(max_length=100)),
                ('etabliss_1', models.CharField(max_length=100)),
                ('type_terrain', models.CharField(max_length=100)),
                ('inspection', models.CharField(max_length=100)),
                ('minister', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'collegeb2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='jardin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canton_nom', models.CharField(max_length=100)),
                ('nom_locali', models.CharField(max_length=100)),
                ('etablissem', models.CharField(max_length=100)),
                ('etab_adr', models.CharField(max_length=100)),
                ('ouverture', models.CharField(max_length=100)),
                ('etabliss_1', models.CharField(max_length=100)),
                ('type_terrain', models.CharField(max_length=100)),
                ('inspection', models.CharField(max_length=100)),
                ('minister', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'jardinb2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='lycee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canton_nom', models.CharField(max_length=100)),
                ('nom_locali', models.CharField(max_length=100)),
                ('etablissem', models.CharField(max_length=100)),
                ('etab_adr', models.CharField(max_length=100)),
                ('ouverture', models.CharField(max_length=100)),
                ('etabliss_1', models.CharField(max_length=100)),
                ('type_terrain', models.CharField(max_length=100)),
                ('inspection', models.CharField(max_length=100)),
                ('minister', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'lyceb2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='marche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canton_nom', models.CharField(max_length=100)),
                ('nom_locali', models.CharField(max_length=100)),
                ('marche_nom', models.CharField(max_length=100)),
                ('jours', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'marche_bli2',
                'managed': False,
            },
        ),
    ]
