# Generated by Django 4.2.20 on 2026-01-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoportail', '0005_college_jardin_lycee_marche'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commune',
            table='blitt2',
        ),
    ]
