# Generated by Django 4.2.20 on 2026-01-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoportail', '0007_alter_commune_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='routes',
            table='routeb2',
        ),
    ]
