# Generated by Django 4.2.20 on 2026-01-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoportail', '0008_alter_routes_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jardin',
            table='jardb2',
        ),
    ]
