# Generated by Django 4.2.20 on 2026-01-29 10:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportail', '0009_alter_jardin_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='pea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canton_nom', models.CharField(max_length=100)),
                ('nom_locali', models.CharField(max_length=100)),
                ('forage_nom', models.CharField(max_length=100)),
                ('forage_typ', models.CharField(max_length=100)),
                ('batiment_n', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'pea',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='lycee',
            table='lyc2',
        ),
    ]
