# Generated by Django 4.2.20 on 2026-01-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoportail', '0010_pea_alter_lycee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='marche',
            table='marches',
        ),
    ]
