# Generated by Django 4.2.20 on 2026-01-29 17:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportail', '0012_bornefontaine'),
    ]

    operations = [
        migrations.CreateModel(
            name='chateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canton_nom', models.CharField(max_length=100)),
                ('nom_locali', models.CharField(max_length=100)),
                ('chateau_no', models.CharField(max_length=100)),
                ('organisme', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'bornefontaines',
                'managed': False,
            },
        ),
    ]
