# Generated by Django 4.2.20 on 2026-01-29 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoportail', '0013_chateau'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chateau',
            table='chateau',
        ),
    ]
