# Generated by Django 4.2.20 on 2026-01-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoportail', '0014_alter_chateau_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chateau',
            table='chatea',
        ),
    ]
