# Generated by Django 4.2.20 on 2026-01-31 17:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportail', '0015_alter_chateau_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='coperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canton_nom', models.CharField(max_length=100)),
                ('nom_locali', models.CharField(max_length=100)),
                ('cooperativ', models.CharField(max_length=100)),
                ('cooperat_1', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'cooperativebl2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='hopitale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canton_nom', models.CharField(max_length=100)),
                ('nom_locali', models.CharField(max_length=100)),
                ('nom_fs', models.CharField(max_length=100)),
                ('ouverture', models.CharField(max_length=100)),
                ('secteur', models.CharField(max_length=100)),
                ('services_p', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'formation_sanitairebl2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='magazinbl2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canton_nom', models.CharField(max_length=100)),
                ('etab_nom', models.CharField(max_length=100)),
                ('ouverture', models.CharField(max_length=100)),
                ('organisme', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'magazin_intrantbl2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canton_nom', models.CharField(max_length=100)),
                ('nom_locali', models.CharField(max_length=100)),
                ('terrain', models.CharField(max_length=100)),
                ('terrain_sp', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'stade_terrainbl2',
                'managed': False,
            },
        ),
    ]
