# Generated by Django 4.2.20 on 2026-01-31 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoportail', '0016_coperative_hopitale_magazinbl2_terrain'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hopitale',
            table='formation_sanitaireb_2',
        ),
    ]
