# Generated by Django 4.2.20 on 2026-01-31 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoportail', '0017_alter_hopitale_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hopitale',
            table='formation_s',
        ),
    ]
